### ISSUE TITLE
Køge bliver ikke nævnt

### ISSUE THREAD

**Issue by jimmiw** [FrederikNordahl/ide#1]
Køge bliver ikke nævnt... og jeg kan heller ikke se den i words.js..

bug?! :)

**Comment by FrederikNordahl** [comment]
Hej Jimmi

Mange tak for din issue beskrivelse!

Dette er opsat som et open source project af netop denne grund. Du er meget velkommen til at tilføje Køge i et pull requets, så lover jeg at jeg måske acceptere.

De bedste hilsner
Frederik
